---

- name: Create Elasticsearch Keystore
  become: yes
  command: >
   {{es_path_home}}/bin/elasticsearch-keystore create
  args: 
    creates: "{{ es_path_conf }}/elasticsearch.keystore"
  environment:
    ES_PATH_CONF: "{{ es_path_conf }}"


- name: Set Elasticsearch Keystore Permissions
  become: yes
  file: state=file path={{ es_path_conf }}/elasticsearch.keystore owner={{ es_owner }} group={{ es_group }} mode={{ es_mode }}


- name: Check if Elasticsearch Keystore is Setup
  become: yes
  command: >
   {{es_path_home}}/bin/elasticsearch-keystore list
  register: list_keystore
  changed_when: false
  environment: 
    ES_PATH_CONF: "{{ es_path_conf }}"
  check_mode: no


- name: Create Bootstrap Password for Elastic User
  become: yes
  shell: echo "{{ es_api_basic_auth_password }}" | {{ es_path_home }}/bin/elasticsearch-keystore add -x 'bootstrap.password'
  when: 
   - es_api_basic_auth_username is defined and list_keystore is defined and es_api_basic_auth_username == 'elastic' and 'bootstrap.password' not in list_keystore.stdout_lines
  environment: 
    ES_PATH_CONF: "{{ es_path_conf }}"
  no_log: true


- name: Include Builtin User Setup
  include_tasks: setup-built-in-user.yml